version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: meal
      POSTGRES_PASSWORD: meal
      POSTGRES_DB: meal
    ports:
      - "5432:5432"
  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://meal:meal@db:5432/meal
      JWT_SECRET: change-me
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5500,http://localhost:5500
    depends_on:
      - db
    ports:
      - "8000:8000"
